### ISSUE TITLE
shallow ice thickness

### ISSUE THREAD

**Issue by Elchin** [whrc/Lake-Model-Data#4]
@ amullen01 in spinup, snow depth is kinda high (1m). We need to check with Jackie on that. I would expect the pond to freeze substantially, it shows only 20 ice thickness.

**Comment by amullen01** [comment]
@Elchin I agree, the snow thickness does look a bit deep and ice thickness low. The snow data input is coming from the McGrath SNOTEL site without bias correction, as I was not able to procure any snow data from anywhere closer the the ponds. We could synthetically reduce it until we get the actual snow data from Jackie.

**Comment by Elchin** [comment]
Based on previous studies, 50cm snow depth serves as a threshold. So snow depth below 50cm should have an impact on ice thickness. If not, we could further reduce it by filtering low winter precipitation data.
